// Auto-generated types from Strapi v5 schema
// Generated on: 2025-07-17T13:10:45.830Z
// Do not edit this file manually - it will be overwritten

export interface StrapiResponse<T> {
  data: T;
  meta: {
    pagination?: {
      page: number;
      pageSize: number;
      pageCount: number;
      total: number;
    };
  };
}

export interface StrapiGraphQLResponse<T> {
  data: {
    [key: string]: T[];
  };
}

export interface StrapiMediaFormat {
  name: string;
  hash: string;
  ext: string;
  mime: string;
  path?: string;
  width: number;
  height: number;
  size: number;
  sizeInBytes: number;
  url: string;
}

export interface StrapiMedia {
  id: number;
  documentId: string;
  name: string;
  alternativeText?: string;
  caption?: string;
  width?: number;
  height?: number;
  formats?: {
    thumbnail?: StrapiMediaFormat;
    mobile?: StrapiMediaFormat;
    tablet?: StrapiMediaFormat;
    desktop?: StrapiMediaFormat;
    wide?: StrapiMediaFormat;
    xlarge?: StrapiMediaFormat;
    webp?: StrapiMediaFormat;
    thumbnail_webp?: StrapiMediaFormat;
    mobile_webp?: StrapiMediaFormat;
    tablet_webp?: StrapiMediaFormat;
    desktop_webp?: StrapiMediaFormat;
    wide_webp?: StrapiMediaFormat;
    xlarge_webp?: StrapiMediaFormat;
  };
  hash: string;
  ext: string;
  mime: string;
  size: number;
  url: string;
  previewUrl?: string;
  provider: string;
  provider_metadata?: Record<string, unknown>;
  createdAt: string;
  updatedAt: string;
  publishedAt: string;
}

export interface MenuItem {
  label: string;
  page?: Page;
  url?: string;
  target?: '_self' | '_blank' | '_parent' | '_top';
  order?: number;
  isActive?: boolean;
  subItems?: SubMenuItem[];
}

export interface SubMenuItem {
  label: string;
  page?: Page;
  url?: string;
  target?: '_self' | '_blank' | '_parent' | '_top';
  order?: number;
  isActive?: boolean;
}

export interface Button {
  text?: string;
  icon?: StrapiMedia;
  type?: 'primary' | 'primary-inverted' | 'secondary' | 'secondary-inverted';
  target?: string;
}

export interface HeroSlider {
  Slides?: Image[];
  autoPlayTimerSec?: number;
  slideEffect: 'slide' | 'fade' | 'flip';
}

export interface Hero {
  picture: StrapiMedia;
  mobileImage?: StrapiMedia;
}

export interface Image {
  image: StrapiMedia;
  mobileImage?: StrapiMedia;
}

export interface SimpleText {
  text?: Record<string, unknown>;
}

export interface TextBox {
  title?: Record<string, unknown>;
  content?: Record<string, unknown>;
  ctas?: Button[];
}

export interface BlockSpacing {
  spacingType: 'none' | 'small' | 'medium' | 'large' | 'xlarge' | 'custom';
  customSpacing?: ResponsiveSpacing;
}

export interface ContentSection {
  margins?: BlockSpacing;
  paddings?: BlockSpacing;
  maxWidth?: 'none' | 'sm' | 'md' | 'lg' | 'xl' | 'max2xl' | 'max3xl' | 'max4xl' | 'max5xl' | 'max6xl' | 'max7xl';
  customClassName?: string;
  inlineStyles?: string;
  content?: Hero | SimpleText | TextBox | Image | HeroSlider;
}

export interface ResponsiveSpacing {
  mobile?: SpacingValues;
  tablet?: SpacingValues;
  desktop?: SpacingValues;
  wide?: SpacingValues;
  xlarge?: SpacingValues;
}

export interface SpacingValues {
  top?: number;
  right?: number;
  bottom?: number;
  left?: number;
}

export interface OpenGraph {
  ogTitle: string;
  ogDescription: string;
  ogImage?: StrapiMedia;
  ogUrl?: string;
  ogType?: string;
}

export interface Seo {
  metaTitle: string;
  metaDescription: string;
  metaImage?: StrapiMedia;
  openGraph?: OpenGraph;
  keywords?: string;
  metaRobots?: string;
  metaViewport?: string;
  canonicalURL?: string;
  structuredData?: unknown;
}

export interface Menu {
  id: number;
  documentId: string;
  name: string;
  slug: string;
  menuItems?: MenuItem[];
}

export interface Page {
  id: number;
  documentId: string;
  title: string;
  slug: string;
  seo?: Seo;
  content?: ContentSection;
}

export interface Redirect {
  id: number;
  documentId: string;
  from: string;
  to: string;
  type?: 'permanent' | 'temporary';
  isActive?: boolean;
}

export interface SiteOption {
  id: number;
  documentId: string;
  siteLogo: StrapiMedia;
  favicon: StrapiMedia;
  headerMenu?: Menu;
  footerMenus?: Menu[];
  homepage?: Page;
  seo: Seo;
  locale: string;
  localizations?: SiteOption[];
  createdAt: string;
  updatedAt: string;
}

